# See https://github.com/realm/SwiftLint#configuration
# See https://realm.github.io/SwiftLint/rule-directory.html

included:
  - LinkLiar
  - LinkTools
  - linkdaemon

disabled_rules:
 - explicit_acl
 - explicit_type_interface
 - indentation_width
 - multiline_arguments_brackets

opt_in_rules:
  # - all
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - direct_return
  - duplicate_imports
  - file_name
  - implicit_return
  - literal_expression_end_indentation
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - self_in_property_initialization
  - sorted_imports
