name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Developer certificate
        run: bin/cert
        env:
          CUSTOM_KEYCHAIN_PASSWORD: ${{ secrets.CUSTOM_KEYCHAIN_PASSWORD }}
          CERTIFICATE_ENCRYPTION_KEY: ${{ secrets.CERTIFICATE_ENCRYPTION_KEY }}

      - name: Run Test Suite
        run: xcodebuild test -scheme LinkLiar | xcpretty
